= Configuration

The `IamId` framework need several configuration to work, as is based on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] need some configuration for this framework but most of this config is already fixed in the `IamId` implementation so even if is passed will be rewritten.

The first thing to highlight is that configuration is split in two types, and at the time to create the `IamId` instance should be pass as different values in the constructor (you can see the examples in <<library.adoc#,API docs>>). This differentiation have a reason let us see each both types:

environment::
A JSON object containing the non sensitive data related with configuration, normally this will be stores in a config server, configmap... in the different environments.

secrets::
A JSON object containing the sensitive information needed for the server, normally this information will be stored in a more secure way as kubernetes secrets, some kind of vault... in the different environments.


== Environment configuration

The next keys are allowed into the environment configuration JSON, the default values for each config can be found in link:../lib/configuration/default-environment.js[default-environment.js]

scopes::
An array of string containing all the allowed scopes in this OP. example `scopes: ['accounts', 'cards']`

claims::
An object containing the exposed claims by this OP, following the format described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider configuration claims]

routes::
An object containing the names of the routes that are exposed by the OP, the routes that can be configured can be see in link:../lib/configuration/default-environment.js[default-environment.js], default values are the recommended nes but can be customized if there are a good reason.

pushedRequestURN::
A urn prefix for generate the request_uri` in the 'initiate-authorize' endpoint, should follow a format as for example `urn:op.example:`, see https://tools.ietf.org/html/rfc8141[URN specification] for more info.

issuer::
The URI of the OP that will be used as `aud` claim in JWT tokens, security...

masks::
An object containing the claims mask definition. See section <<Claims Mask>> for more info.

postLogoutRedirectURI::
The url where End-User will be redirect after a /logout request.

customAuthorizationEndpoint::
The authorization endpoint showed in the '/.well-known/openid-configuration' endpoint is automatically calculated by oidc-provider library, to customize and use an external web just use this property.

ttl::
Expirations for all token types, as described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#ttl[oidc-provider documentation]

== Secret configuration

This file contain values that are supposed to be 'secrets' (confidential) like keys, passwords... there are two main sections:

clients:: An array of static client configuration as defined in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#clients[oidc-provider configuration client].
jwks:: A Json Web Key Set that contain the keys that will be used by the OP for sign and encrypt.
pairwiseSalt:: A secret text to be used as a salt for calculate the pairwise user identifier as described in https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg[oidc Section 8.1.]
cookies:: The cookies configurtaion for the server, as described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#cookies[oidc-provider configuration cookies]

This file is intentionally separated from the config so you can store in a more secure way like in a Kubernetes secret, vault solution...

repositories::


== Fixed configuration



== Claims Mask


== How to provide the configuration?



{
  discovery: {
    assertion_claims_supported: true,
    digital_id_certified_data_extension: true,
    claims_in_assertion_claims_supported: {
      total_balance: { type: 'object', properties: { amount: { type: 'decimal' }, currency: { type: 'string' } } },
      phone_number: { type: 'phone_number' },
      email: { type: 'string' },
      birthdate: { type: 'date' },
      family_name: { type: 'string' },
      given_name: { type: 'string' }
    },
    assertion_claims_query_language_supported: {
      string: ['$eq'],
      phone_number: ['$eq'],
      date: ['$eq', '$gt', '$lt', '$gte', '$lte'],
      decimal: ['$eq', '$gt', '$lt', '$gte', '$lte'],
      object: []
    }
  },
  masks: {
    email: { type: 'email' },
    phone_number: { type: 'slice', args: { prefix: '******', begin: -4 } },
    given_name: { type: 'fill', args: { begin: 2, end: -2, filling: '****' } },
    family_name: { type: 'fill', args: { begin: 2, end: -2, filling: '****' } }
  },
  ttl: {
    AccessToken: 1,
    AuthorizationCode: 120,
    ClientCredentials: 1,
    DeviceCode: 1,
    IdToken: 600
  },
  whitelistedJWA: {
    tokenEndpointAuthSigningAlgValues: ['RS256'],
    idTokenSigningAlgValues: ['RS256'],
    requestObjectSigningAlgValues: ['RS256'],
    userinfoSigningAlgValues: ['RS256']
  },
  clockTolerance: 5
}
