= Configuration

The `IamId-provider` framework need several configuration to work, because is based on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] need some configuration for this framework, most of config values are already fixed in the `IamId-provider` please see <<'Fixed configuration'>> section for more info, the rest of the values should be provided by the developer on startup.

The first thing to highlight is that configuration is split in two types, and at the time to create the `IamId` instance should be pass as different parameters in the constructor (you can see the examples in <<library.adoc#,API docs>>).

This differentiation have a reason let us see each both types:

environment::
A JSON object containing the non sensitive data related with configuration, normally this will be stores in a config server, configmap... in the different environments.

secrets::
A JSON object containing the sensitive information needed for the server, normally this information will be stored in a more secure way as kubernetes secrets, some kind of vault... in the different environments.

== Environment configuration

The next keys are allowed into the environment configuration JSON, the default values for each config can be found in link:../lib/configuration/default-environment.js[default-environment.js]

scopes::
An array of string containing all the allowed scopes in this OP. example `scopes: ['accounts', 'cards']`

claims::
An object containing the exposed claims by this OP, following the format described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider configuration claims]

routes::
An object containing the names of the routes that are exposed by the OP, the different routes that can be configured are listed in file link:../lib/configuration/default-environment.js[default-environment.js], default values are the recommended ones but can be customized if there are a good reason.

pushedRequestURN::
A urn prefix for generate the `request_uri` in the 'initiate-authorize' endpoint, should follow a URN format as for example `urn:op.example:`, see https://tools.ietf.org/html/rfc8141[URN specification] for more info.

issuer::
The URI of the OP that will be used as `aud` claim in JWT tokens, security...

masks::
An object containing the claims mask definition. See page <<claimmask.adoc#,Claims Mask>> for more info about this feature.

postLogoutRedirectURI::
The url where End-User will be redirect after a /logout request.

customAuthorizationEndpoint::
The authorization endpoint showed in the '/.well-known/openid-configuration' endpoint is automatically calculated by oidc-provider library, to customize and use an external web just use this property.

ttl::
Expirations for all token types, as described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#ttl[oidc-provider documentation]

whitelistedJWA::
This is also a configuration from https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#whitelistedjwa[oidc-provider] and declare the supported algorithms for each operation.

clockTolerance::
Also from https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#clocktolerance[oidc-provider] this value is a Number value (in seconds) describing the allowed system clock skew for validating client-provided JWTs, e.g. Deafult value is `5` seconds.

discovery::
Is a JSON object that provide additional information in the discovery document (`.well-known` endpoint), for implement the IAMID profile some values should be defined here:
* assertion_claims_supported: A boolean that indicates if the OP support `assertion_claims`.
* digital_id_certified_data_extension: A boolean value that indicate if this OP support the IAMID profile.
* claims_in_assertion_claims_supported: An object describing what of the exposed claims support assertions, also provide the type of the claim. The key inside the object is the name of the claim, so for exmaple `birthdate: { type: 'date' }` means that `birthdate` claim is of type `date`.
* assertion_claims_query_language_supported: An Object that contain as keys the name of the claim type and as values an array with all the operators that this type support. For example `string: ['$eq']` means that claims of type string support the `$eq` operator.

See complete example in file link:../lib/configuration/default-environment.js[default-environment.js]

== Secret configuration

The next keys are allowed into the environment configuration JSON, the default values for each config can be found in link:../lib/configuration/default-secret.js[default-secret.js]

clients::
An array of static clients definition (RP), the configuration description can be found on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#clients[oidc-provider configuration client] an important thing to highlight is that in the IAMID profile all clients must use `private_key_jwt` as authentication so all params related with that should be correctly setup (`token_endpoint_auth_method`, `token_endpoint_auth_signing_alg`, `jwks`, ...)

jwks::
A Json Web Key Set that contain the keys that will be used by the OP for sign and encrypt. The object must be in https://tools.ietf.org/html/rfc7517#section-5[JWK Set format] and all provided keys must be private keys. PLease refer to https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#jwks[oidc-provider jwks] for more info about supported key types and more.

pairwiseSalt::
A secret text to be used as a salt for calculate the pairwise user identifier as described in https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg[oidc Section 8.1.]

cookies::
The cookies configuration for the OP server, afull description of this config can be found on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#cookies[oidc-provider configuration cookies]

repositories::
All data in the OP Server from the request object to the access token are storage in a repository in a temporal way (everything expire), for this the iamid-provider uses a repository pattern, to setup this configuration the `repositories` config field is a JSON object that contain one entry for each entity as for example:
----
{
  'session': { ... },
  'access_token': { ... },
  'consents': { ... },
  'default': { ... }
  ...
}
----
If you don't want to define a concrete entity you can use `default`, this config will be applied to all entities that are not defined.

Inside the repo config for each entity in this moment there are two types of repository:

* Memory: Is the default implementation when you don't provide a `repositories` configuration but is not a good options for Production environment. Just keep the config empty for this entity as for example `session: { }`
* MongoDB: Store the entities in a MongoDB collection. The configuration should be as

----
{
  { 'default': { type: 'mongodb', 'options': { 'uri': 'mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[database][?options]]' } } }
}
----

The `uri` parameter is a mongo connection string, you can read more about this in official MongoDb documentation https://docs.mongodb.com/manual/reference/connection-string/[here]

By last to define the indexes for the repo collections in mongo you just need to at as `repository` config top root level one entry with the key being the name of the entity plus `-mongodb-indexes` and the value an array of MongoDB index values. For example:
----
  'session-mongodb-indexes': [
    { key: { uid: 1 }, unique: true }
  ]
----

== Fixed configuration

Some of the configuration that is provided by the https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] that this library use as base is fixed purposely because the IAMID profile has restrictive requirements and https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] implement lot of OIDC flavors. This fixed config even if is provided by the developer will be overwritten, have look to the file link:../lib/configuration/fixed.js[fixed.js] to know this values.

== How to provide the configuration?

The way to store, manage and obtain the configuration is out of the scope of this library, you can choose to use a config-map, kubernetes secret, environment variables, a spring config server... but once obtained in your code you need to provide both config objects `secrets` and `environments` when creating the `IAmId` app as follow:

----
const { IAmId } = require('iamid-provider')
const app = new IAmId(environment, secrets)
----

To know more in deep about how to initialize the server you can read docs on <<server.adoc#,Putting all together and starting the server>>

