= Configuration
:toc:

`IamId-provider` framework need some configuration to work, one of the reasons is because is based on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md[oidc-provider] and allow to personalize the behavior using several configurations.

For the case of the config for `oidc-provider` most of config values are already fixed in the `IamId-provider`, see <<Fixed configuration>> section for more info, the rest of the values should be provided by the developer on startup.

The first thing to highlight is that we have two different types of configuration that has different priority when merge (see more about that later), the different type of configurations are:

environment::
Contain the non sensitive data in the configuration, normally this will be stores in a config server, config-map... in the different environments.

secrets::
Contain the sensitive information needed for the server, normally this information will be stored in a more secure way as kubernetes secrets, some kind of vault... in the different environments.


== Environment configuration

The next keys are allowed into the environment configuration JSON, the default values for each config can be found in link:../lib/configuration/default-environment.js[default-environment.js]

scopes::
An array of string containing all the allowed scopes in this OP. example `scopes: ['accounts', 'cards']`

claims::
An object containing the exposed claims by this OP, following the format described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider configuration claims]

routes::
An object containing the names of the routes that are exposed by the OP, the different routes that can be configured are listed in file link:../lib/configuration/default-environment.js[default-environment.js], default values are the recommended ones but can be customized if there are a good reason.

pushedRequestURN::
A urn prefix for generate the `request_uri` in the 'initiate-authorize' endpoint, should follow a URN format as for example `urn:op.example:`, see https://tools.ietf.org/html/rfc8141[URN specification] for more info.

issuer::
The URI of the OP that will be used as `aud` claim in JWT tokens, security...

masks::
An object containing the claims mask definition. See page <<claimmask.adoc#,Claims Mask>> for more info about this feature.

postLogoutRedirectURI::
The url where End-User will be redirect after a /logout request.

customAuthorizationEndpoint::
The authorization endpoint showed in the '/.well-known/openid-configuration' endpoint is automatically calculated by oidc-provider library, to customize and use an external web just use this property.

ttl::
Expirations for all token types, as described in https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#ttl[oidc-provider documentation]

whitelistedJWA::
This is also a configuration from https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#whitelistedjwa[oidc-provider] and declare the supported algorithms for each operation.

clockTolerance::
Also from https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#clocktolerance[oidc-provider] this value is a Number value (in seconds) describing the allowed system clock skew for validating client-provided JWTs, e.g. Deafult value is `5` seconds.

discovery::
Is a JSON object that provide additional information in the discovery document (`.well-known` endpoint), for implement the IAMID profile some values should be defined here:
* assertion_claims_supported: A boolean that indicates if the OP support `assertion_claims`.
* digital_id_certified_data_extension: A boolean value that indicate if this OP support the IAMID profile.
* claims_in_assertion_claims_supported: An object describing what of the exposed claims support assertions, also provide the type of the claim. The key inside the object is the name of the claim, so for exmaple `birthdate: { type: 'date' }` means that `birthdate` claim is of type `date`.
* assertion_claims_query_language_supported: An Object that contain as keys the name of the claim type and as values an array with all the operators that this type support. For example `string: ['eq']` means that claims of type string support the `eq` operator.

See complete example in file link:../lib/configuration/default-environment.js[default-environment.js]

== Secret configuration

The next keys are allowed into the environment configuration JSON, the default values for each config can be found in link:../lib/configuration/default-secret.js[default-secret.js]

clients::
An array of static clients definition (RP), the configuration description can be found on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#clients[oidc-provider configuration client] an important thing to highlight is that in the IAMID profile all clients must use `private_key_jwt` as authentication so all params related with that should be correctly setup (`token_endpoint_auth_method`, `token_endpoint_auth_signing_alg`, `jwks`, ...)

jwks::
A Json Web Key Set that contain the keys that will be used by the OP for sign and encrypt. The object must be in https://tools.ietf.org/html/rfc7517#section-5[JWK Set format] and all provided keys must be private keys. PLease refer to https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#jwks[oidc-provider jwks] for more info about supported key types and more.

pairwiseSalt::
A secret text to be used as a salt for calculate the pairwise user identifier as described in https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg[oidc Section 8.1.]

cookies::
The cookies configuration for the OP server, afull description of this config can be found on https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#cookies[oidc-provider configuration cookies]

repositories::
All data in the OP Server from the request object to the access token are storage in a repository in a temporal way (everything expire), for this the iamid-provider uses a repository pattern, to setup this configuration the `repositories` config field is a JSON object that contain one entry for each entity as for example:
----
{
  'session': { ... },
  'access_token': { ... },
  'consents': { ... },
  'default': { ... }
  ...
}
----
If you don't want to define a concrete entity you can use `default`, this config will be applied to all entities that are not defined.

Inside the repo config for each entity in this moment there are two types of repository:

* Memory: Is the default implementation when you don't provide a `repositories` configuration but is not a good options for Production environment. Just keep the config empty for this entity as for example `session: { }`
* MongoDB: Store the entities in a MongoDB collection. The configuration should be as

----
{
  { 'default': { type: 'mongodb', 'options': { 'uri': 'mongodb://[username:password@]host1[:port1][,...hostN[:portN]][/[database][?options]]' } } }
}
----

The `uri` parameter is a mongo connection string, you can read more about this in official MongoDb documentation https://docs.mongodb.com/manual/reference/connection-string/[here]

By last to define the indexes for the repo collections in mongo you just need to at as `repository` config top root level one entry with the key being the name of the entity plus `-mongodb-indexes` and the value an array of MongoDB index values. For example:
----
  'session-mongodb-indexes': [
    { key: { uid: 1 }, unique: true }
  ]
----

== Fixed configuration

Some of the configuration provided to https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] is fixed inside the `iamid-provider` code, the reason for this is because IAMID profile has restrictive requirements and https://github.com/panva/node-oidc-provider/blob/master/docs/README.md#claims[oidc-provider] implement lot of OIDC flavors. This fixed config even if is provided by the developer will be overwritten, have look to the file link:../lib/configuration/fixed.js[fixed.js] if ou want to know this values. If you think some of this values need to be configurable for some use case please open a issue to let us know.

== How to provide the configuration?

The way to store, manage and obtain the configuration is out of the scope of this library, you can choose to use a config-map, kubernetes secret, environment variables, a spring config server... but once obtained in your code you need to provide a 'merged' configuration object when creating the `IAmId` app. To 'merge' all the configuration `iamid-provider` provide a `Configuration` class that allow you to add one or more configuration object of each type and calling the `build()` method will be merged with the default and fixed values to obtain a one merged configuration object, let us see an example of use:

.Configuration object
[source,javascript]
----
const { Configuration } = require('@santander/iamid-provider')

const config = Configuration
  .newInstance()
  .pushSecrets(secrets)
  .pushEnvironment(defaultEnvConfig)
  .pushEnvironment(environment)
  .build()

const app = new IAmId(config, router, repositories, resolver)
----

In the example we provide one secret config and two environment configs, in the case of the environments config we are providing a default configuration and then the config obtained from this environment, see section <<Configuration priority/order>> for more info about config priority.

Once obtained the merged config we can pass to the `IAmId` constructor as show in the example. To know more in deep about how to initialize the server you can read docs on <<server.adoc#,Putting all together and starting the server>>

== Configuration priority/order

The 'secret' configuration has more priority than 'environment' config, this means if the same key appear in both types the value in 'secret' overwrite the value in 'environment'.

The priority of provided config is by order so if we push two environment config the second one will overwrite the values in the first one, the same for secrets.

The fixed config described in <<Fixed configuration>> has the maximum priority, values in fixed will overwrite values in any configuration type (environment or secrets).

The `iamid-provider` library comes with some default values that has the minimum priority, any value pass in secret or environment config will overwrite the defined default values.
