= iamid-provider
:toc:
:toc-placement!:

`iamid-provider` is a NodeJs framework on top of an open source OpenId connect implementation https://github.com/panva/node-oidc-provider[oidc-provider], so this product implement an OAuth 2.0 Authorization Server with OpenID Connect and put in top of that the IAMID profile.

toc::[]

== What is IAMID profile?

Is a work in progress profile on top of OpenId connect that will allow OPs share customer data in a way that is secure, respect the privacy of the customer, is reliable, release the minimum quantity of information and has an assurance level.

== What are the implemented specs & features?

`iamid-provider` is based in https://github.com/panva/node-oidc-provider[oidc-provider] that implement lot of specification (can be consult in the product github) but the goal of this implementation is the IAMID profile so several specficiation/fetaure has been limited or deactivated and another ones added to the implementation, the supported specs/features are:

* IAMID Authorization Code flow
* https://openid.net/specs/openid-connect-discovery-1_0.html[OpenID Connect Discovery 1.0]
* https://openid.net/specs/openid-connect-registration-1_0.html[OpenID Connect Dynamic Client Registration 1.0]
* https://openid.net/specs/oauth-v2-form-post-response-mode-1_0.html[OAuth 2.0 Form Post Response Mode]
* https://tools.ietf.org/html/rfc7636[RFC7636 - Proof Key for Code Exchange (PKCE)]
* https://tools.ietf.org/html/rfc8252[RFC8252 - OAuth 2.0 for Native Apps BCP (AppAuth)]
* https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-03[JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens - draft 03]
* https://tools.ietf.org/html/draft-ietf-oauth-par-00[OAuth 2.0 Pushed Authorization Requests - draft 00]
* https://tools.ietf.org/html/draft-ietf-cose-webauthn-algorithms-03[JWS ES256K / JWK secp256k1 JOSE support - draft 03]

Some other specification can be supported when using the https://github.com/panva/node-oidc-provider[oidc-provider] configuration but are not recommended because of the risk to break some of the IAMID features.

== How to use the library?

`iamid-provider` is provided as a library for implement an OP (Openid Provider), so for example using `npm` you can install in your project using:

[source,bash]
----
npm install --save @santander/aimid-provider
----

Doing an export of the library we will get available different utils exposes by the library, an early definition can be found in <<library.adoc#,IAMID API>>

Once exported the library we need to implement/develop some pieces to create our own OP server, the steps are:

* <<config.adoc#,Provide configuration to IAMID>>
* <<connectors.adoc#,Implement the connectors>>
* <<endpoints.adoc#,Implement the interactions endpoints>>
* <<server.adoc#,Putting all together and starting the server>>

A good start point could be to use the https://uk-gitlab.almuk.santanderuk.corp/verified-id/op-server[Santander-uk project] as base and modify the code there.
