= Running Server

After setup our <<config.adoc#,config>>, create the <<connectors.adoc#,connectors>> and implement the <<endpoints.adoc#,interactions endpoints>> is time to put all together and can't be more easy, as commented before you can use as reference the https://uk-gitlab.almuk.santanderuk.corp/verified-id/op-server[Santander-uk project] but let us see an example in code here:

.OpServer.js
----
const { IAmId, Configuration, Repositories } = require('@santander/iamid-provider') <1>
const InteractionRouter = require('./interaction-router')
const MyConnector = require('./connector')

<2>
// Config load
const secrets = require('../config/secrets')
const environment = require('../config/environment')
const defaultEnvConfig = require('./default-env-config')
const config = Configuration
  .newInstance()
  .pushSecrets(secrets)
  .pushEnvironment(defaultEnvConfig)
  .pushEnvironment(environment)
  .build()

const repositories = new Repositories(config.repositories) <3>
const connector = new MinibankConnector(repositories) <4>
const router = new InteractionRouter(login) <5>
const app = new IAmId(config, router, repositories, connector) <6>

<7>
const port = process.env.PORT || 8080
app.listen(port, () => {
  logger.info(`${pkg.name} listening on port ${port}`)
}).on('close', () => {
  repositories.close() <8>
})

----
<1> Import `IAmId` from `iamid-provider`
<2> Merge the configuration using the `Configuration` class, you can have as many sources as you want, this is better explained in <<config.adoc#,config>>.
<3> We need to instantiate the `Repositories`, see <<repositories.adoc#,respositories>> for more info.
<4> Instantiate our connector. Remember that should be a `proxyResolvers` object.
<5> Instantiate our interaction router, see <<endpoints.adoc#,interactions endpoints>> for more info.
<6> Create the instance of the `IAmId` app, passing the config, the router, repositories instance and the connector.
<7> Initialize the app and start listening on port 8080.
<8> On server stop we should close the repositories.

That's All!!

